version: '3.8'

services:
  php:
    image: php:8.1-cli
    container_name: queue-php
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    command: >
      sh -c "apt-get update && 
             apt-get install -y libsqlite3-dev && 
             docker-php-ext-install pdo_sqlite &&
             php -S 0.0.0.0:8000 -t public"
    networks:
      - queue-network

  node:
    image: node:18-alpine
    container_name: queue-node
    working_dir: /app
    volumes:
      - ./:/app
    command: >
      sh -c "npm install && npm run dev"
    networks:
      - queue-network

networks:
  queue-network:
    driver: bridge
