version: '3.8'

services:
  php:
    image: php:8.1-cli
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    working_dir: /app
    command: >
      sh -c "
        apt-get update && 
        apt-get install -y libsqlite3-dev && 
        docker-php-ext-install pdo_sqlite &&
        php -S 0.0.0.0:8000 -t public
      "